//auth connect
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_END = 'AUTH_END';
export const AUTH_CLEAN_UP = 'AUTH_CLEAN_UP';
export const AUTH_RECOVER_PW_START = 'AUTH_RECOVER_PW_START';
export const AUTH_RECOVER_PW_SUCCESS = 'AUTH_RECOVER_PW_SUCCESS';
export const AUTH_RECOVER_PW_FAIL = 'AUTH_RECOVER_PW_FAIL';
export const AUTH_RECOVER_PW_END = 'AUTH_RECOVER_PW_END';
export const AUTH_CONNECT_GUEST = 'AUTH_CONNECT_GUEST';
export const AUTH_DISCONECT_GUEST = 'AUTH_DISCONECT_GUEST';

export const TASK_ADD = 'TASK_ADD';
export const TASK_ADD_SUCCESS = 'TASK_ADD_SUCCESS';
export const TASK_ADD_FAIL = 'TASK_ADD_FAIL';
export const TASK_DELETE_END = 'TASK_DELETE_END';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL';
export const TASK_ADD_NODB = 'TASK_ADD_NODB';
export const TASK_SELECT_NODB = 'TASK_SELECT_NODB';
export const TASK_DELETE_NODB = 'TASK_DELETE_NODB';
export const TASK_COMPLETE_NODB = 'TASK_COMPLETE_NODB';
export const TASK_DELETE_ALL_COMPLETED_NODB = 'TASK_DELETE_ALL_COMPLETED_NODB';
export const TASK_EDIT_NODB = 'TASK_EDIT_NODB';
export const TASK_SAVE_TIME_SPENT_NODB = 'TIMER_SAVE_TIME_SPENT_NODB';

export const UI_TOGGLE_NAV = 'UI_TOGGLE_NAV';
export const UI_TOGGLE_ADD_TASK = 'UI_TOGGLE_ADD_TASK';
export const UI_TOGGLE_MODAL = 'UI_TOGGLE_MODAL';
export const UI_CLOSE_NAV = 'UI_CLOSE_NAV';
export const UI_OPEN_LOGIN = 'UI_OPEN_LOGIN';
export const UI_OPEN_CREATE = 'UI_OPEN_CREATE';

export const TIMER_START = 'TIMER_START';
export const TIMER_STOP = 'TIMER_STOP';
